# stack build plan using GHC 8.4.3 and recent stackage nightly

resolver: nightly-2018-06-02

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
# hledger-ui
# newer fsnotify has a different api and may be more robust
- fsnotify-0.3.0.1
- cassava-megaparsec-1.0.0

nix:
  pure: false
  packages: [perl gmp ncurses zlib]
